package net.zuperz.aurora.Entity.client;


import com.mojang.math.Transformation;
import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class VoidWalkerAnimations {
        public static final AnimationDefinition IDLE = AnimationDefinition.Builder.withLength(1.9583433f).looping()
                .addAnimation("Head",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(7.5f, 5f, 5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(3.08f, 3.98f, 12.45f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(7.71f, 4.67f, 7.49f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.9583433f, KeyframeAnimations.degreeVec(7.5f, 5f, 5f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Head",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Mave",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(-5f, 0.22f, -2.51f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.9583433f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Mave",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("R_arm",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(5f, 0f, -7.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(5.02f, 4.98f, -7.06f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.9583433f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("R_arm",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("L_arm",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(7.5f, 0f, 12.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(2.4f, -3.66f, 1.94f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.9583433f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("L_arm",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("R_leg",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("L_leg",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(0f, 0f, 1.2f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.9583433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("L_leg",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("VoidWalker",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.375f, KeyframeAnimations.posVec(0f, -1f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("VoidWalker",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("R_leg2",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 3.7f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.5f, KeyframeAnimations.degreeVec(2.2f, 0.19f, 2.3f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.9583433f, KeyframeAnimations.degreeVec(0f, 0f, 3.7f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("R_leg2",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR))).build();
        public static final AnimationDefinition WALK = AnimationDefinition.Builder.withLength(2.3433335f).looping()
                .addAnimation("VoidWalker",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.375f, KeyframeAnimations.posVec(0f, -1f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("VoidWalker",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("R_leg",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Mave",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, -1f, -1f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.0416765f, KeyframeAnimations.posVec(0f, -1f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.3433335f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Mave",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5f, KeyframeAnimations.degreeVec(-4.98f, 0.44f, 2.48f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(9.94f, 1.3f, -2.44f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(-4.98f, 0.44f, 2.48f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.0416765f, KeyframeAnimations.degreeVec(7.44f, 1.3f, -2.44f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.3433335f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Mave",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("R_arm",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(-13.04f, -12.19f, -4.3f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(9.96f, 0.87f, -10.66f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.3433335f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("R_arm",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("L_arm",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 7.5f, 2.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1f, KeyframeAnimations.degreeVec(14.95f, -1.29f, 8.01f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(-3.95f, -5.51f, 6.57f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.3433335f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("L_arm",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Head",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(7.5f, 5f, 5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5f, KeyframeAnimations.degreeVec(-6.28f, -4.19f, -11.64f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(-18.78f, -4.19f, -11.64f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.375f, KeyframeAnimations.degreeVec(0.55f, -6.37f, -2.32f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.3433335f, KeyframeAnimations.degreeVec(7.5f, 5f, 5f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Head",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("L_leg",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9583434f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.0416765f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.3433335f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("L_leg",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 0f, -1.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(-8.76f, -0.27f, -7.02f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.125f, KeyframeAnimations.degreeVec(9.99f, 0.33f, -1.22f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.625f, KeyframeAnimations.degreeVec(0f, 0f, -1.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2f, KeyframeAnimations.degreeVec(-6.26f, -0.27f, -7.02f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.1676665f, KeyframeAnimations.degreeVec(12.24f, 0.21f, -2.38f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.2083435f, KeyframeAnimations.degreeVec(7.49f, 0.33f, -1.22f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.3433335f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("L_leg",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("R_leg2",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.4583433f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.1676667f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.375f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.6766667f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("R_leg2",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 3.7f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-8.76f, -0.27f, 7.02f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.625f, KeyframeAnimations.degreeVec(19.99f, 0.33f, 1.22f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(-8.76f, -0.27f, 7.02f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.5416767f, KeyframeAnimations.degreeVec(14.99f, 0.33f, 1.22f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.0834335f, KeyframeAnimations.degreeVec(-2.77f, 0.1f, 2.92f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.3433335f, KeyframeAnimations.degreeVec(0f, 0f, 3.7f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("R_leg2",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Jar",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(1.61f, -1.5f, -1.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.375f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.9167667f, KeyframeAnimations.degreeVec(2.61f, -2.5f, -2.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Eyes",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR))).build();
        public static final AnimationDefinition ATTACK = AnimationDefinition.Builder.withLength(0.7916766f)
                .addAnimation("VoidWalker",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("R_leg",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Mave",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7916766f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Mave",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.125f, KeyframeAnimations.degreeVec(12.5f, 0f, -2.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(27.5f, 0f, -2.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(25f, 0f, -2.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(27.22f, 0f, -2.5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Mave",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("R_arm",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("R_arm",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("L_arm",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("L_arm",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Head",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5416766f, KeyframeAnimations.posVec(0f, 0f, -1.25f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7083434f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Head",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(7.5f, 5f, 5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-17.5f, 5f, 5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(-2.86f, 5f, 5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(2.5f, 5f, 5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(7.5f, 5f, 5f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Head",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("L_leg",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("R_leg2",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 3.7f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("R_leg2",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Eyes",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.625f, KeyframeAnimations.degreeVec(-17.49f, 1.63f, -3.14f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Eyes",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Jar",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(4.98f, 0.44f, -4.98f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("Jar",
                        new AnimationChannel(AnimationChannel.Targets.SCALE,
                                new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                        AnimationChannel.Interpolations.LINEAR))).build();
}